services:
  scala-api:
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8081:8081

  broker:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mqtt:/mosquitto/config 
    ports:
      - 1883:1883
      - 8080:8080

  db:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=cattracker
      - POSTGRES_USER=myuser
      - POSTGRES_PORT=5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
