version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=cattracker
      - POSTGRES_USER=myuser
      - POSTGRES_PORT=5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080