services:
  scala-api:
    build:
      dockerfile: ./Dockerfile
      network: host
    network_mode: "host"

  db:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=cattracker
      - POSTGRES_USER=myuser
      - POSTGRES_PORT=5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080